### ISSUE TITLE
ImmediatelyFastReforged crashes my modded Minecraft for some reason

### ISSUE THREAD

**Issue by Raconzer** [CCr4ft3r/ImmediatelyFastReforged#3]
[crash-2023-05-17_16.28.29-client.txt](https://github.com/CCr4ft3r/ImmediatelyFastReforged/files/11499357/crash-2023-05-17_16.28.29-client.txt)

**Comment by CCr4ft3r** [comment]
Please provide your latest.log via https://gist.github.com/. The crash report does not include the actual cause.

**Comment by Raconzer** [comment]
> Please provide your latest.log via https://gist.github.com/. The crash report does not include the actual cause.

I have never used GitHub before, could you please let me know how to upload my latest.log or guide me on what to search in Google so I can follow some steps to do it?

**Comment by CCr4ft3r** [comment]
You can click on the link above. Then you can open your latest.log and copy the content of it. You can paste it into the text field of the opened site. After that you can click on the button "create secret gist" and provide the link to your gist here.

**Comment by CCr4ft3r** [comment]
An alternative is for example pastebin.com

**Comment by OcrSu** [comment]
I also encountered the same problem today.

However, after I updated the Forge version to 40.2.4 and removed some of the affiliated mods that were not compatible with the new version of Forge or the latest version of Create Mod.

The problem has disappeared.

> An alternative is for example pastebin.com

**Comment by CCr4ft3r** [comment]
The official version now supports Forge. Therefore the port is discontinued.
