### ISSUE TITLE
Icon issue on Xaero's minimap

### ISSUE THREAD

**Issue by 131iodine** [CCr4ft3r/ImmediatelyFastReforged#6]
These weird textures are used as icons for some skeletons that spawn with armor on Xaero's minimap.
![Untitled](https://github.com/CCr4ft3r/ImmediatelyFastReforged/assets/73848389/dca95d5b-b6ab-4ad7-9553-a43da4760d9f)

Screen without Immediately Fast Reforged
![2](https://github.com/CCr4ft3r/ImmediatelyFastReforged/assets/73848389/f4844de4-d21d-4c57-a5ae-a9efc68b1e40)

**Comment by CCr4ft3r** [comment]
:( I will check on these next week

**Comment by 131iodine** [comment]
Okay, now I am not sure that it's Immediately Fast issue

"I doubt the issue is on their end, tbh. Thanks for the info" - Xaero's reply

**Comment by CCr4ft3r** [comment]
So does it still happened when removing ImmediatelyFast from your modpack? If yes, then it's an issue of Xaero's worldmap - if not it's an issue of ImmediatelyFast

**Comment by CCr4ft3r** [comment]
They probably don't know this mod - however I will take a look into this issue

**Comment by 131iodine** [comment]
Thank you. If you need help with reproducing it let me know.

**Comment by CCr4ft3r** [comment]
The official version now supports Forge. Therefore the port is discontinued.
