### ISSUE TITLE
Weird entity rendering

### ISSUE THREAD

**Issue by DragonMaster14545** [CCr4ft3r/ImmediatelyFastReforged#8]
When having this mod installed, the outlines of the block you are looking at are not where they should be and have a random size. Same happens with some block entitys and normal mods.
![Screenshot (244)](https://github.com/CCr4ft3r/ImmediatelyFastReforged/assets/114180377/eb86429f-726d-4e4a-84a9-5c656a2b61db)

**Comment by CCr4ft3r** [comment]
The official version now supports Forge. Therefore the port is discontinued.
