### ISSUE TITLE
Botania crash

### ISSUE THREAD

**Issue by kurtramone** [CCr4ft3r/ImmediatelyFastReforged#9]
Crash with Botania on 1.19.2 while viewing preview for multi block enchantment from Botania's book

No crashes without Immediately Fast Reforged

**Comment by CCr4ft3r** [comment]
Please provide the log or the crash report including the exception

**Comment by kurtramone** [comment]
Here it is
[2023-08-04-3.log](https://github.com/CCr4ft3r/ImmediatelyFastReforged/files/12267675/2023-08-04-3.log)

**Comment by kurtramone** [comment]
Sorry, forgot crash report

[crash-2023-08-04_22.00.44-client.txt](https://github.com/CCr4ft3r/ImmediatelyFastReforged/files/12267907/crash-2023-08-04_22.00.44-client.txt)

**Comment by kurtramone** [comment]
Any news? Botânica uses Patouli and I guess more mods have this same issue
